# Generated by Django 4.0.1 on 2022-01-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dog_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dog_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/dogs/'),
        ),
    ]
