# Generated by Django 4.0.1 on 2022-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_profile_dog_description_profile_dog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dog_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
