# Generated by Django 4.0.1 on 2022-02-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_profile_username_alter_profile_dog_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
