# Generated by Django 4.0.1 on 2022-05-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='on_minddescription',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_image',
        ),
    ]
