# Generated by Django 4.0.1 on 2022-05-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_profile_age_remove_profile_breed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='province',
        ),
    ]
