# Generated by Django 4.0.1 on 2022-05-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_profile_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='on_mind',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_image',
            new_name='image',
        ),
    ]
