# Generated by Django 4.0.1 on 2022-05-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_rename_on_mind_profile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='breed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
