# Generated by Django 4.0.1 on 2022-05-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_profile_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='month',
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
