# Generated by Django 4.0.1 on 2022-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_rename_age_profile_month_profile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
