# Generated by Django 4.0.1 on 2022-05-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
