# Generated by Django 4.0.1 on 2022-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_list_clicked',
            field=models.TextField(blank=True, null=True),
        ),
    ]
