# Generated by Django 4.0.1 on 2022-05-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_profile_username_list_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matched_usernames',
            field=models.TextField(blank=True, null=True),
        ),
    ]
